apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-microservice-config
data:
  SERVICE_NAME: "notifications-microservice"
---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-microservice-secret
type: Opaque
data:
  SECRET_KEY: "cDlDVEFCRzE2cFMrVWJoZnNnRHpQSHE3MXZjaWphcXc5dmwwMXJaZ3dTS1hqY0RYYURnbGQrd3piY2hRaCtxUVc9PQ=="
  TOKEN_ALGORITHM: "SFM1MTI="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-microservice
  template:
    metadata:
      labels:
        app: notifications-microservice
    spec:
      containers:
      - name: notifications-microservice
        command: ["uvicorn", "delvify.main:ms", "--host", "0.0.0.0", "--port", "8000"]
        image: ajijii/notifications-microservice
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: notifications-microservice-config
        - secretRef:
            name: users-microservice-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-microservice-service
spec:
  selector:
    app: notifications-microservice
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8000
