apiVersion: v1
kind: PersistentVolume
metadata:
  name: lists-microservice-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/lists-microservice-db-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lists-microservice-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lists-microservice-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lists-microservice-db
  template:
    metadata:
      labels:
        app: lists-microservice-db
    spec:
      containers:
      - name: lists-microservice-db
        image: postgres:15.3
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: lists-microservice-db-volume
        envFrom:
          - secretRef:
              name: lists-microservice-secret
      volumes:
      - name: lists-microservice-db-volume
        persistentVolumeClaim:
          claimName: lists-microservice-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lists-microservice-db-service
spec:
  selector:
    app: lists-microservice-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
