apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice-app
  template:
    metadata:
      labels:
        app: users-microservice-app
    spec:
      containers:
      - name: users-microservice-app
        command: ["uvicorn", "delvify.main:ms", "--host", "0.0.0.0", "--port", "8000"]
        image: ajijii/users-microservice
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: users-microservice-config
          - secretRef:
              name: users-microservice-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-microservice-app-service
spec:
  selector:
    app: users-microservice-app
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8000
