apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        command: ["serve", "-s", "."]
        image: ajijii/web-client
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-service
spec:
  type: NodePort
  selector:
    app: web-client
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 3000
